---
variables:
  GIT_SUBMODULE_STRATEGY: normal
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

.test:
  stage: test
  script: "mvn test -D bridj.debug=true"

test:jdk8-alpine:
  extends: .test
  image: maven:3-jdk-8-alpine
  before_script:
    - "apk add libc6-compat libstdc++"
    - "export LD_LIBRARY_PATH=/lib64/"

test:jdk8:
  extends: .test
  image: maven:3-jdk-8
  
test:jdk11-slim:
  extends: .test
  image: maven:3-jdk-11-slim

test:jdk11:
  extends: .test
  image: maven:3-jdk-11

test:centos7:
  extends: .test
  image: centos:7
  before_script:
    - "yum install -y maven"