---
variables:
  GIT_SUBMODULE_STRATEGY: normal
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

.test:
  stage: test
  script: "mvn test -D bridj.debug=true"

test:jdk8-alpine:
  extends: .test
  image: maven:3-jdk-8-alpine
  before_script:
    - "apk add libc6-compat libstdc++"
    - "export LD_LIBRARY_PATH=/lib64/"

test:jdk8:
  extends: .test
  image: maven:3-jdk-8

test:jdk11-slim:
  extends: .test
  image: maven:3-jdk-11-slim

test:jdk11:
  extends: .test
  image: maven:3-jdk-11

.centos:
  extends: .test
  before_script:
    - "yum install -y maven"

test:centos7:
  extends: .centos
  image: centos:7

test:centos8:
  extends: .centos
  image: centos:8

.ubuntu:
  extends: .test
  before_script:
    - "apt update"
    - "apt install -y default-jdk-headless maven"

test:ubuntu20:
  extends: .ubuntu
  image: ubuntu:20.04

test:ubuntu19:
  extends: .ubuntu
  image: ubuntu:19.10

test:ubuntu18:
  extends: .ubuntu
  image: ubuntu:18.04

test:ubuntu16:
  extends: .ubuntu
  image: ubuntu:16.04

.fedora:
  extends: .test
  before_script:
    - "dnf install -y maven"

test:fedora33:
  extends: .fedora
  image: fedora:33

test:fedora32:
  extends: .fedora
  image: fedora:32

test:fedora31:
  extends: .fedora
  image: fedora:31