jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Maven@3
  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: Maven@3
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: Maven@3